<template>
  <div class="loadingio-spinner-pulse-6cspz7ixusk" v-if="show == true">
    <div class="ldio-9un9b4kn35d">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Loader",
  props: ["show"]
};
</script>

<style  scoped>
@keyframes ldio-9un9b4kn35d-1 {
  0% {
    top: 36px;
    height: 128px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-9un9b4kn35d-2 {
  0% {
    top: 41.99999999999999px;
    height: 116.00000000000001px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-9un9b4kn35d-3 {
  0% {
    top: 48px;
    height: 104px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
.ldio-9un9b4kn35d div {
  position: absolute;
  width: 30px;
}
.ldio-9un9b4kn35d div:nth-child(1) {
  left: 35px;
  background: #e15b64;
  animation: ldio-9un9b4kn35d-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.2s;
}
.ldio-9un9b4kn35d div:nth-child(2) {
  left: 85px;
  background: #f8b26a;
  animation: ldio-9un9b4kn35d-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.1s;
}
.ldio-9un9b4kn35d div:nth-child(3) {
  left: 135px;
  background: #abbd81;
  animation: ldio-9un9b4kn35d-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-6cspz7ixusk {
  z-index: 1000;
  opacity: .5; /* in FireFox */ 
    filter: alpha(opacity=50); /* in IE */
  position: absolute;
  top: 30%;
  left: 40%;
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-9un9b4kn35d {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-9un9b4kn35d div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>